packages:
  - services/*
  - domains/*
  - packages/*

injectWorkspacePackages: true

onlyBuiltDependencies:
  - sharp
  - unrs-resolver
  - esbuild

overrides:
  '@opentelemetry/api': ^1.9.0
  '@opentelemetry/core': ^1.25.1
  'sucrase>glob': 10.5.0

savePrefix: ''

syncInjectedDepsAfterScripts:
  - build
