### Create a Feature Flag
POST http://localhost:3000/api/flags
Content-Type: application/json

{
  "productId": "<product-id>",
  "envId": "<environment-id>",
  "label": "test",
  "enabled": true,
  "description": "Test feature flag",
  "gates": [
    {
      "type": "all",
      "value": true
    }
  ]
}